name: 🤖 Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        go-version: [1.19]

    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "./ci/stack.yml" up -d --build

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: test/package-lock.json

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: |
          go run . &
          cd test
          npm ci
          npm test

      - name: Stop containers
        if: always()
        run: docker-compose -f "./ci/stack.yml" down