name: 🤖 Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose --env-file .env -f "./ci/stack.yml" up -d --build

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: test/package-lock.json

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        working-directory: ./test
        run: |
          npm ci
          npm test

      - name: Stop containers
        if: always()
        run: docker-compose --env-file .env -f "./ci/stack.yml" down
